eval_report this repo have evalution pipeline.
skit-ai/skit-pipelines pull request #126
Opened 2023-10-18 10:30 UTC by deepak-aryak9

pipeline name - evaluate_slu
required params - {
"repo_name": "tvs-in",
"repo_branch": "sandbox", Not mandatory.
"test_dataset_path":"s3://vernacular-ml/deepak/aliased_data.csv"
}
with aliased file -- -
{
"repo_name": "tvs-in",
"repo_branch": "sandbox",
"test_dataset_path":"s3://vernacular-ml/deepak/76_-06-28-32-tagged.csv",
"alias_yaml_path": "intents/tvs_india/alias.yaml"
}

2023-10-18 11:13 UTC, ltbringer commented
Is it necessary to have the raw bucket path on the description?

- Buckets contain sensitive information.
- Bad actors crawl in search for leaking tokens, bucket paths etc.
- Even if a bucket is private, the path gives enough hints to discover other objects. Like one can guess there are prefixes same as employee names. Thanks to Linkedin I can loop through employees to discover paths that aren't private.

2023-11-03 09:31 UTC, harshithere requested changes
One major change is breaking the current retrain pipeline as well into components. Else, I'm assuming you have tested the changes and that both pipelines still work

2023-11-03 09:31 UTC, harshithere commented on skit_pipelines/components/evaluate_slu_from_repo/__init__.py
> +    from skit_pipelines.components.retrain_slu_from_repo.comparision_report_generator import \
Not needed imports

2023-11-03 09:31 UTC, harshithere commented on skit_pipelines/components/evaluate_slu_from_repo/__init__.py
> +    # testing the model that was just trained
Nitpick: Update the comments

2023-11-03 09:31 UTC, harshithere commented on skit_pipelines/components/evaluate_slu_from_repo/__init__.py
> +    if os.path.exists(pipeline_constants.OLD_DATA):
This can be removed (you are not copying data to OLD_DATA path)

2023-11-22 13:28 UTC, harshithere approved these changes
Good work.
Have a couple of minor changes. Can you attach some successful test runs in the description (both of new `evaluate_slu` and existing `retrain_slu`)

2023-11-22 13:28 UTC, harshithere commented on skit_pipelines/components/evaluate_slu_from_repo/__init__.py
> +    compare = True if compare_branch else False
Nitpick: This compare variable is not needed. Values in `compare_branch` (checking if its !="") can do the same check

2023-11-22 13:28 UTC, harshithere commented on skit_pipelines/components/utils_slu.py
> +        if os.path.exists("data.dvc"):
Not needed condition. If `compare_branch` exisits, this value must be there

2023-11-22 13:28 UTC, harshithere commented on skit_pipelines/pipelines/evaluate_slu/__init__.py
> +    validate_evaluation_setup_op = evalution_slu_from_repo_op(
Question: How much time does evaluate take normally? If its a few minutes, then we dont need to validate the setup and can remove this

2023-11-22 13:28 UTC, harshithere commented on skit_pipelines/pipelines/evaluate_slu/__init__.py
> +        s3_paths=test_dataset_path,
You dont need `s3_path` and `labelstudio_project_ids` in evaluate_slu. Please remove these variables

2023-11-29 16:20 UTC, merged