Fix metrics missing in data folder
skit-ai/skit-pipelines pull request #152
Opened 2024-02-28 08:55 UTC by d-shree

Fixes for the following issues -

1. Metrics folder not found in the data/classification folders
2. Upload not working for s3, due to incompatible regions

2024-03-01 10:20 UTC, harshithere requested changes
Some changes suggested

2024-03-01 10:20 UTC, harshithere commented on skit_pipelines/components/evaluate_slu_from_repo/__init__.py
> +    if compare:
Question: Why do you have this? The value of `compare` comes from `compare_branch` anyway in Line 42

2024-03-01 10:20 UTC, harshithere commented on skit_pipelines/components/upload2s3.py
> +    region_name: str = ""
Suggestion: We dont need this as a variable. A mapping could get the `region_name` from the `bucket_name` passed. Would reduce one variable and chances of the caller making a mistake. Instead have a dict as:

```
region_mapper = {
'bucket_1': 'region_1',
'bucket_2': 'region_2'...}
```

2024-03-04 06:29 UTC, d-shree commented on skit_pipelines/components/upload2s3.py
> +    region_name: str = ""
Makes sense, will try this.

2024-03-04 12:48 UTC, d-shree commented on skit_pipelines/components/evaluate_slu_from_repo/__init__.py
> +    if not compare:
Done

2024-03-04 12:54 UTC, merged