pushing eevee intent metrics to db.
skit-ai/skit-pipelines pull request #39
Opened 2022-08-02 05:26 UTC by greed2411

`irr_from_tog` now has `mlwr=True` pipeline arg (which also requires `lang`, `slu_project_name`) for pushing calculated eevee metrics on a tog job to events db.

2022-08-02 05:36 UTC, biswaroop1547 requested changes

2022-08-02 05:36 UTC, biswaroop1547 commented on skit_pipelines/components/push_irr_to_postgres.py
> +    ML_METRICS_DB_PASSWORD = os.environ["ML_METRICS_DB_PASSWORD"]
can we define these under constants.py and then call it?

2022-08-02 05:36 UTC, biswaroop1547 commented on skit_pipelines/components/push_irr_to_postgres.py
> +    """
should go under constants.py too

2022-08-02 05:36 UTC, biswaroop1547 commented on skit_pipelines/components/push_irr_to_postgres.py
> +    )
can we remove the example from here and add it as a section under irr_from_tog docstring on how to get this behaviour through charon?

2022-08-02 05:37 UTC, greed2411 commented on skit_pipelines/components/push_irr_to_postgres.py
> +    )
this helps with running things locally. i can comment it out  if you want.

2022-08-02 05:53 UTC, biswaroop1547 commented on skit_pipelines/components/push_irr_to_postgres.py
> +    )
yep okay, would be helpful if you could add a section on this in docs with example values

2022-08-02 06:07 UTC, greed2411 commented on skit_pipelines/components/push_irr_to_postgres.py
> +    ML_METRICS_DB_PASSWORD = os.environ["ML_METRICS_DB_PASSWORD"]
this already existed.

2022-08-02 06:07 UTC, greed2411 commented on skit_pipelines/components/push_irr_to_postgres.py
> +    """
moved it out there

2022-08-02 06:09 UTC, greed2411 commented
found an issue, where all the irr-metrics/events are getting pushed to ingio's name. (because i thought app_id wouldn't matter). but it actually matters. want to explore if we are okay with creating a new table for this.

2022-08-04 16:52 UTC, greed2411 commented on skit_pipelines/components/push_irr_to_postgres.py
> +    )
done. added docstring containing mlwr=True example.

2022-08-04 16:53 UTC, greed2411 commented
the PR is good for merging and it is working as expected. please go ahead with the pull request.

2022-08-05 05:57 UTC, greed2411 commented
have written bit of code, introduced a component to extract data out of the tagged content etc to populate the intent_metrics table.
now it is ready for review. sorry for the to & fro.

2022-08-05 05:59 UTC, greed2411 commented
resolved merge conflicts.

2022-08-05 08:22 UTC, greed2411 commented
`raw` column as messed up sorry!

2022-08-05 14:05 UTC, greed2411 commented
had to fix the `raw` column output. now using the json dump of the classification_report, we can rebuild it on metabase.
example looking metabase question: https://metabase.skit.ai/question/4838-classification-report-intent-metrics?intent_metrics_id=11
for the run: https://kubeflow.skit.ai/_/pipeline/?ns=skit#/runs/details/5b946f60-4800-42a1-8607-6cdd01ee308f

please have a look at it and give me feedback. this is the final PR review request for real.

2022-08-07 20:58 UTC, biswaroop1547 approved these changes

2022-08-07 20:59 UTC, merged