add files for fetch_tagged_entity_dataset pipeline.
skit-ai/skit-pipelines pull request #54
Opened 2022-08-30 13:03 UTC by greed2411

ignore the branch name, but adding a new pipeline called `fetch_tagged_entity_dataset`. it gives modified entity tog dataset which is ready for eval (for changelog.md)

This takes a tog job, and the annotated region tagged texts & entity types -> hits duckling to get the `value` parameter.
it also mutates the predicted entities structure to be sane and comparable with truth.

the resulting columns which are ready for evaluation: `truth_entities_with_duckling` & `predicted_entities_with_modifications` can be compared directly using eevee.

successful runs for this pipeline (for american finance & mahindra finance) are here:
https://kubeflow.skit.ai/pipeline/#/runs/details/74db9af8-2963-47ec-8c94-c6b85b2cc002
https://kubeflow.skit.ai/pipeline/#/runs/details/491ebe4a-53bf-486e-8317-c3ba9ccd64a0

2022-08-30 13:04 UTC, greed2411 commented
cc: @nilesh-skit @piyushmakhija5 @janaab11

2022-08-30 18:07 UTC, biswaroop1547 requested changes

2022-08-30 18:07 UTC, biswaroop1547 commented on skit_pipelines/components/modify_tog_entities.py
> +
this component file looks too big, can you break it down to different modules and keep it inside a directory? something similar to the `tag_calls` component.

2022-08-31 05:02 UTC, greed2411 commented on skit_pipelines/components/modify_tog_entities.py
> +
done.

2022-08-31 05:03 UTC, greed2411 commented
have made the changes requested, please lmk if there is anything else.

2022-08-31 06:17 UTC, biswaroop1547 approved these changes

2022-08-31 06:17 UTC, merged