Transcription Pipeline V2
skit-ai/skit-pipelines pull request #56
Opened 2022-09-06 05:25 UTC by iamsh4shank

So as of now - 

- I reused the download from s3 bucket to download file from the s3. 
- Created a new component to convert the audio using Johhny
- Created a new component to transcribe using Blaze
- Created a new component to merge the transcription with the actual CSV file
- Pushed back again the updated CSV to S3 bucket.

2022-09-06 05:56 UTC, tanmay17061 requested changes
needs major refactoring. co-work session required.

2022-09-06 05:56 UTC, tanmay17061 commented on skit_pipelines/pipelines/transcription_pipeline/__init__.py
> +        asr_transcription_op("output_folder", "../../utils/resources_blaze/config_azure.yaml")
1. Can't have local paths (eg- `"../../utils/resources_blaze/"`) inside pipeline or component code. Let's assume the config is a file uploaded to s3 and provided as an argument by the user for now.
2. Also, since config is coming from the user, we don't need the `asr_model` argument. Blaze can figure the ASR from the config.

2022-09-06 05:56 UTC, tanmay17061 commented on skit_pipelines/pipelines/transcription_pipeline/__init__.py
> +    s3_path: str,
Input parameter name not indicative of what the path is for. Should use something like `s3_path_data`.

2022-09-06 05:56 UTC, tanmay17061 commented on skit_pipelines/pipelines/transcription_pipeline/__init__.py
> +    audio_data = download_from_s3_op(storage_path = s3_path, output_path = "")
Can't pass anything to `output_path`, that's not how paths work in kubeflow. Also, naming of `audio_data` can be better (eg- `original_data_op`
Use something like:
```
original_data_op = download_from_s3_op(storage_path = s3_path_data)
# now the downloaded csv can be accessed using: `original_data_op.outputs["output"]`
```

2022-09-06 05:56 UTC, tanmay17061 commented on skit_pipelines/pipelines/transcription_pipeline/__init__.py
> +    audio_csv = merge_transcription_csv_op("results.sqlite", audio_data)
Once again, not the correct way to use paths.
Use this instead:
```
asr_op = asr_transcription_op("output_folder", #download config from s3 and pass the path here)
merged_data_op = merge_transcription_csv_op(asr_op.outputs["output"], audio_data)
```

2022-09-06 05:56 UTC, tanmay17061 commented on skit_pipelines/utils/resources_blaze/config_google.yaml
> +          - ये एजेंट को दूंगा में कैश में क्योंकि अकाउंट से तो कटे नहीं है
can't have config to be static, need it configurable by the user.

2022-09-06 12:10 UTC, biswaroop1547 commented
+1 with @tanmay17061's review and please keep all pipeline related code till `skit_pipelines/pipelines` and `skit_pipelines/components` only.

2022-09-06 12:11 UTC, biswaroop1547 requested changes
+1 with @tanmay17061's review and please keep all pipeline related code till skit_pipelines/pipelines and skit_pipelines/components only.

2022-09-06 12:25 UTC, ltbringer commented
Is shashank an actual contributor?

On Tue, 6 Sept 2022, 17:41 Biswaroop Bhattacharjee, <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> +1 with @tanmay17061 <https://github.com/tanmay17061>'s review and please
> keep all pipeline related code till skit_pipelines/pipelines and
> skit_pipelines/components only.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/skit-ai/skit-pipelines/pull/56#pullrequestreview-1097466982>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC4P6CIVZXXVABL5I2ZBUYDV44YHPANCNFSM6AAAAAAQFPACEM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-09-06 13:01 UTC, biswaroop1547 commented
@ltbringer Shashank is working as an ml intern and contributing to this as it's part of the ASR pod initiative and he is a part of it.

2022-09-14 00:56 UTC, biswaroop1547 commented on skit_pipelines/utils/resources_blaze/config_google.yaml
> +          - ये एजेंट को दूंगा में कैश में क्योंकि अकाउंट से तो कटे नहीं है
@tanmay17061 this is required
> please keep all pipeline related code till skit_pipelines/pipelines and skit_pipelines/components only

I think this can be put under skit_pipelines/component/<turn your respective blaze component into dir and keep those files there, take reference from tag_calls component dir or preprocess dir>

2022-09-14 01:04 UTC, biswaroop1547 requested changes

2022-09-14 01:04 UTC, biswaroop1547 commented on skit_pipelines/utils/resources_blaze/config_kaldi.yaml
> +        max_alternatives: 10
[this is required](https://github.com/skit-ai/skit-pipelines/pull/56/files#r970199773) as utils directory should only contain api level utilities.

2022-09-14 01:04 UTC, biswaroop1547 commented on skit_pipelines/utils/resources_blaze/confiq_azure.yaml
> +        model: default
[this is required](https://github.com/skit-ai/skit-pipelines/pull/56/files#r970199773) as utils directory should only contain api level utilities.

2022-09-14 04:18 UTC, iamsh4shank commented on skit_pipelines/utils/resources_blaze/config_google.yaml
> +          - ये एजेंट को दूंगा में कैश में क्योंकि अकाउंट से तो कटे नहीं है
I think we can remove this, as of now we are taking config directly from the user

2022-09-14 04:18 UTC, iamsh4shank commented on skit_pipelines/utils/resources_blaze/config_google.yaml
> +          - ये एजेंट को दूंगा में कैश में क्योंकि अकाउंट से तो कटे नहीं है
I think we can remove this, as of now we are taking config directly from the user

2022-09-14 05:55 UTC, iamsh4shank commented on skit_pipelines/utils/resources_blaze/confiq_azure.yaml
> +        model: default
We can remove this, as we are taking config as an input from the user.

2022-09-14 15:43 UTC, biswaroop1547 approved these changes

2022-09-14 15:45 UTC, merged