Feat: LM Tuning V2 using TOG job ID
skit-ai/skit-pipelines pull request #64
Opened 2022-09-15 12:44 UTC by iamsh4shank

2022-09-16 05:20 UTC, tanmay17061 requested changes

2022-09-16 05:20 UTC, tanmay17061 commented on skit_pipelines/pipelines/asr_tune/__init__.py
> +    val_corpus_tog_job_ids: str = None,
Let's keep the default value as `""` for these 4 variables. eg-
```
corpus_path: str = "",
...
```

2022-09-16 05:20 UTC, tanmay17061 commented on skit_pipelines/pipelines/asr_tune/__init__.py
> +    with kfp.dsl.Condition(corpus_path == None):
change to:
```
with kfp.dsl.Condition(corpus_path == "","corpus_path"):
```

2022-09-16 05:20 UTC, tanmay17061 commented on skit_pipelines/pipelines/asr_tune/__init__.py
> +    with kfp.dsl.Condition(corpus_tog_job_ids == None):
change to:
```
with kfp.dsl.Condition(corpus_tog_job_ids == "","corpus_path")
```

2022-11-29 08:54 UTC, biswaroop1547 commented
stale, hence closing.

2022-11-29 08:54 UTC, closed without merging