new pipeline for pushing same data for intent, entities & slot/call tagging
skit-ai/skit-pipelines pull request #81
Opened 2022-11-22 05:10 UTC by greed2411

2022-11-23 07:17 UTC, biswaroop1547 requested changes

2022-11-23 07:17 UTC, biswaroop1547 commented on skit_pipelines/components/tag_calls/__init__.py
> +    labelstudio_call_project_id : Optional[str] = None,
can we call this `call_project_id`

2022-11-24 09:09 UTC, greed2411 commented on skit_pipelines/components/tag_calls/__init__.py
> +    labelstudio_call_project_id : Optional[str] = None,
want to be explicit about labelstudio man.

2022-11-24 11:51 UTC, biswaroop1547 commented on skit_pipelines/components/tag_calls/__init__.py
> +    labelstudio_call_project_id : Optional[str] = None,
since we ditching tog anyway, our params should be annotation tool agnostic

2022-11-24 12:23 UTC, biswaroop1547 requested changes

2022-11-24 12:32 UTC, greed2411 commented on skit_pipelines/components/tag_calls/__init__.py
> +    labelstudio_call_project_id : Optional[str] = None,
lol fine.

2022-11-24 12:54 UTC, greed2411 commented
have made the necessary changes

2022-11-24 12:56 UTC, biswaroop1547 approved these changes

2022-11-24 12:56 UTC, merged